version: '3'

services:
  web:
    build: .
    command: >
      sh -c "./wait-for-it.sh db:5432 -t 30 &&
            python manage.py migrate &&
            python manage.py cargar_productos &&
            python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=patarescata.settings
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '1'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
