# Generated by Django 5.0.2 on 2024-03-02 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apppatarescata', '0002_usuario_email_verificado_usuario_token_verificacion'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
    ]
