# Generated by Django 5.0.2 on 2024-11-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppatarescata', '0004_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='enlace',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
