# Generated by Django 5.0.2 on 2024-11-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppatarescata', '0005_producto_enlace'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('comida', 'Comida para Perros'), ('juguetes', 'Juguetes para Perros')], default='comida', max_length=20),
        ),
    ]
