# Generated by Django 5.2.5 on 2025-08-23 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppatarescata', '0006_producto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('contenido', models.TextField()),
                ('resumen', models.TextField(blank=True, max_length=300)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('categoria', models.CharField(choices=[('adopcion', 'Adopción'), ('cuidados', 'Cuidados'), ('entrenamiento', 'Entrenamiento'), ('salud', 'Salud'), ('medioambiente', 'Medio Ambiente'), ('viajes', 'Viajes con Mascotas')], default='cuidados', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('publicado', models.BooleanField(default=False)),
                ('destacado', models.BooleanField(default=False)),
                ('visitas', models.PositiveIntegerField(default=0)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Artículo del Blog',
                'verbose_name_plural': 'Artículos del Blog',
                'ordering': ['-fecha_publicacion', '-fecha_creacion'],
            },
        ),
    ]
