# Generated by Django 5.2.5 on 2025-08-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppatarescata', '0007_articuloblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopcion',
            name='comentario_fundacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adopcion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='adopcion',
            name='fecha_resolucion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
