# Generated by Django 5.2.5 on 2025-08-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppatarescata', '0008_adopcion_comentario_fundacion_adopcion_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
