# Generated by Django 5.2.5 on 2025-08-25 16:30

import apppatarescata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppatarescata', '0010_usuario_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='token_verificacion',
            field=models.CharField(default=apppatarescata.models.generar_token, max_length=100),
        ),
    ]
