# Generated by Django 5.2.5 on 2025-08-25 16:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppatarescata', '0011_alter_usuario_token_verificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopcion',
            name='fecha_solicitud',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
