# Generated by Django 5.2.5 on 2025-08-27 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppatarescata', '0012_adopcion_fecha_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotafundacion',
            name='adoptante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas_fundacion', to=settings.AUTH_USER_MODEL),
        ),
    ]
