# Generated by Django 5.2.5 on 2025-08-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppatarescata', '0013_alter_mascotafundacion_adoptante'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='tipo_mascota',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
