# Generated by Django 5.2.5 on 2025-08-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppatarescata', '0014_mascota_tipo_mascota'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_perfil/', verbose_name='Imagen de Perfil'),
        ),
    ]
