# Generated by Django 5.2.5 on 2025-09-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppatarescata', '0015_usuario_imagen_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rut_empresa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='mascotafundacion',
            unique_together={('mascota', 'adoptante')},
        ),
    ]
