# Generated by Django 5.2.5 on 2025-09-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppatarescata', '0016_alter_usuario_rut_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='compatible_departamento',
            field=models.CharField(choices=[('si', 'Sí, ideal para departamento'), ('con_restricciones', 'Sí, con restricciones (balcón necesario)'), ('no', 'No, requiere casa con patio')], default='si', max_length=20, verbose_name='Compatible con departamento'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='necesidad_atencion',
            field=models.CharField(choices=[('baja', 'Baja - Independiente'), ('media', 'Media - Necesita compañía moderada'), ('alta', 'Alta - Requiere mucha atención')], default='media', max_length=20, verbose_name='Necesidad de atención'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='nivel_energia',
            field=models.CharField(choices=[('bajo', 'Bajo - Tranquilo y relajado'), ('medio', 'Medio - Activo pero moderado'), ('alto', 'Alto - Muy activo y enérgico')], default='medio', max_length=20, verbose_name='Nivel de energía'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='requisitos_espacio',
            field=models.CharField(choices=[('poco_espacio', 'Poco espacio - Interior pequeño'), ('espacio_moderado', 'Espacio moderado - Interior amplio'), ('mucho_espacio', 'Mucho espacio - Requiere patio o jardín')], default='espacio_moderado', max_length=20, verbose_name='Requisitos de espacio'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='sociabilidad',
            field=models.CharField(choices=[('independiente', 'Independiente - Prefiere estar solo'), ('sociable', 'Sociable - Le gusta la compañía'), ('muy_sociable', 'Muy sociable - Necesita interacción constante')], default='sociable', max_length=20, verbose_name='Nivel de sociabilidad'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='tiempo_ejercicio',
            field=models.CharField(choices=[('poco', 'Poco - 30 minutos o menos'), ('moderado', 'Moderado - 1-2 horas'), ('mucho', 'Mucho - 2+ horas diarias')], default='moderado', max_length=20, verbose_name='Tiempo de ejercicio necesario'),
        ),
    ]
