# Generated by Django 5.2.5 on 2025-09-05 00:48

import apppatarescata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppatarescata', '0017_mascota_compatible_departamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('fecha_suscripcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de suscripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Suscripción activa')),
                ('token_confirmacion', models.CharField(default=apppatarescata.models.generar_token, max_length=40, unique=True, verbose_name='Token de confirmación')),
                ('confirmado', models.BooleanField(default=False, verbose_name='Email confirmado')),
            ],
            options={
                'verbose_name': 'Suscripción al Newsletter',
                'verbose_name_plural': 'Suscripciones al Newsletter',
                'ordering': ['-fecha_suscripcion'],
            },
        ),
    ]
